---
#############################
# PLAY 1: Monitoring agents #
#############################
- name: Node Exporter Instalation
  hosts: all
  become: yes
  vars:
    node_exporter_version: "1.7.0"

  tasks:
    - name: Creating system group
      ansible.builtin.group:
        name: node_exporter
        system: yes

    - name: Creating system users
      ansible.builtin.user:
        name: node_exporter 
        group: node_exporter
        system: yes
        create_home: no
        shell: /bin/false

    - name: Downloading and unzipping binaries in /tmp
      ansible.builtin.unarchive:
        src: "https://github.com/prometheus/node_exporter/releases/download/v{{ node_exporter_version }}/node_exporter-{{ node_exporter_version }}.linux-amd65.tar.gz" 
        dest: /tmp/
        remote_src: yes

    - name: Installing executables in /usr/local/bin
      ansible.builtin.copy:
        src: 'node_exporter-{{ node_exporter_version }}.linux-amd65/node_exporter'
        dest: '/usr/local/bin/node_exporter'
        remote_src: yes
        owner: node_exporter
        group: node_exporter
        mode: '0755'
      notify: SELinux context restore for Node Exporter

    - name: Creating Node Exporter service in Systemd
      ansible.builtin.copy:
        dest: /etc/systemd/system/node_exporter.service
        content: |
          [Unit]
          Description=Node Exporter
          Wants=network-online.target
          After=network-online.target

          [Service]
          User=node_exporter
          Group=node_exporter
          Type=simple
          ExecStart=/usr/local/bin/node_exporter

          [Install]
          WantedBy=multi-user.target
      notify: Restart node_exporter

    - name: Opening Firewalld ports
      ansible.posix.firewalld:
        port: 9100/tcp 
        permanent: yes
        state: enabled
        immediate: yes

  handlers:
    - name: SELinux context restore for Node Exporter
      ansible.builtin.command: restorecon -Rv /usr/local/bin/node_exporter

    - name: Restart node_exporter
      ansible.builtin.systemd:
        name: node_exporter
        state: restarted
        daemon_reload: yes
        enabled: yes


###########################
# PLAY 2: Metrics backend #
###########################
- name: Installing and configuring Prometheus
  hosts: prometheus
  become: yes
  vars:
    prometheus_version: "2.51.0"

  tasks:
    - name: Creating prometheus group
      ansible.builtin.group:
        name: prometheus
        system: yes

    - name: Creating prometheus user
      ansible.builtin.user:
        name: prometheus
        group: prometheus
        system: yes
        create_home: no
        shell: /bin/false

    - name: Creating Prometheus directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        owner: prometheus
        group: prometheus
        mode: '0755'
      loop:
        - /etc/prometheus
        - /var/lib/prometheus

    - name: Downloading and unzipping Prometheus binary
      ansible.builtin.unarchive:
        src: "https://github.com/prometheus/prometheus/releases/download/v{{ prometheus_version }}/prometheus-{{ prometheus_version }}.linux-amd64.tar.gz"
        dest: /tmp/
        remote_src: yes

    - name: Installing Prometheus executables in /usr/local/bin
      ansible.builtin.copy:
        src: "/tmp/prometheus-{{ prometheus_version }}.linux-amd64/{{ item }}"
        dest: "/usr/local/bin/{{ item }}"
        remote_src: yes
        owner: prometheus
        group: prometheus
        mode: '0755'
      loop:
        - prometheus
        - promtool
      notify: SELinux context restore for Prometheus

    - name: Copying consoles directories
      ansible.builtin.copy:
        src: "/tmp/prometheus-{{ prometheus_version }}.linux-amd64/{{ item }}"
        dest: "/etc/prometheus/{{ item }}"
        remote_src: yes
        owner: prometheus
        group: prometheus
      loop:
        - consoles
        - console_libraries

    - name: Generating new prometheus.yml configuration file
      ansible.builtin.copy:
        dest: /etc/prometheus/prometheus.yml
        owner: prometheus
        group: prometheus
        mode: '0644'
        content: |
          global:
            scrape_interval: 15s

          scrape_configs:
            - job_name: "prometheus"
              static_configs:
                - targets: ["localhost:9090"]

            - job_name: "node_exporter"
              static_configs:
                - targets: 
                  - "192.168.75.15:9100"
                  - "192.168.75.16:9100"
      notify: Restart prometheus

    - name: Creating Prometheus service in Systemd
      ansible.builtin.copy:
        dest: /etc/systemd/system/prometheus.service
        content: |
          [Unit]
          Description=Prometheus
          Wants=network-online.target
          After=network-online.target

          [Service]
          User=prometheus
          Group=prometheus
          Type=simple
          ExecStart=/usr/local/bin/prometheus \
              --config.file /etc/prometheus/prometheus.yml \
              --storage.tsdb.path /var/lib/prometheus/ \
              --web.console.templates=/etc/prometheus/consoles \
              --web.console.libraries=/etc/prometheus/console_libraries
          Restart=on-failure

          [Install]
          WantedBy=multi-user.target
      notify: Restart prometheus

    - name: Opening Prometheus ports in Firewalld
      ansible.posix.firewalld:
        port: 9090/tcp
        permanent: yes
        state: enabled
        immediate: yes

  handlers:
    - name: SELinux context restore for Prometheus
      ansible.builtin.command: restorecon -Rv /usr/local/bin/prometheus /usr/local/bin/promtool
      
    - name: Restart prometheus
      ansible.builtin.systemd:
        name: prometheus
        state: restarted
        daemon_reload: yes
        enabled: yes


##################################
# PLAY 3: Frontend visualization #
##################################
- name: Installing and configuring Grafana
  hosts: grafana
  become: yes
  vars:
    grafana_version: "10.4.0"

  tasks:
    - name: Crear¡ting grafana system group
      ansible.builtin.group:
        name: grafana
        system: yes

    - name: Creating grafana system user
      ansible.builtin.user:
        name: grafana
        group: grafana
        system: yes
        create_home: no
        shell: /bin/false

    - name: Downloading and unzipping Grafana binary
      ansible.builtin.unarchive:
        src: "https://dl.grafana.com/oss/release/grafana-{{ grafana_version }}.linux-amd64.tar.gz"
        dest: /usr/local/
        remote_src: yes
        creates: "/usr/local/grafana-v{{ grafana_version }}"

    - name: Creating symbolic link to Grafana
      ansible.builtin.file:
        src: "/usr/local/grafana-v{{ grafana_version }}"
        dest: /usr/local/grafana
        state: link

    - name: Fixing Grafana directory permissions
      ansible.builtin.file:
        path: /usr/local/grafana-v{{ grafana_version }}
        state: directory
        owner: grafana
        group: grafana
        recurse: yes

    - name: Creating Grafana service in Systemd
      ansible.builtin.copy:
        dest: /etc/systemd/system/grafana.service
        content: |
          [Unit]
          Description=Grafana
          Wants=network-online.target
          After=network-online.target

          [Service]
          User=grafana
          Group=grafana
          Type=simple
          WorkingDirectory=/usr/local/grafana
          ExecStart=/usr/local/grafana/bin/grafana-server
          Restart=on-failure

          [Install]
          WantedBy=multi-user.target
      notify: Restart grafana

    - name: Opening Grafana port in Firewalld
      ansible.posix.firewalld:
        port: 3000/tcp
        permanent: yes
        state: enabled
        immediate: yes

  handlers:
    - name: Restart grafana
      ansible.builtin.systemd:
        name: grafana
        state: restarted
        daemon_reload: yes
        enabled: yes
